# Generated by Django 5.2.4 on 2025-07-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("free_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
