# Generated by Django 5.2.4 on 2025-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_broker_user_stock_user_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
