# Generated by Django 5.2.4 on 2025-07-19 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0008_monthlydeposit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyPortfolioSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "total_invested_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_portfolio_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_free_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "total_profit_loss",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "profit_loss_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "unique_together": {("user", "snapshot_date")},
            },
        ),
    ]
