# Generated by Django 5.2.4 on 2025-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0009_monthlyportfoliosnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyportfoliosnapshot",
            name="profit_loss_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="monthlyportfoliosnapshot",
            name="total_profit_loss",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=15, null=True
            ),
        ),
    ]
