# Generated by Django 5.2.4 on 2025-07-21 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stocks",
            "0010_alter_monthlyportfoliosnapshot_profit_loss_percentage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
